#!/bin/sh

set -eu

revision_range="${1?revision range}"

valid=0
revisions=$(git rev-list --reverse "$revision_range")
total=$(echo $revisions | wc -w)
if [ "$total" -eq 0 ]; then
	exit 0
fi
tmp=$(mktemp)
trap "rm -f $tmp" EXIT

allowed_trailers="
Fixes
Closes
Link
Cc
Suggested-by
Requested-by
Reported-by
Co-authored-by
Signed-off-by
Tested-by
Reviewed-by
Acked-by
Assisted-by
"

n=0
title=
fail=false

err() {
	echo "error [$n/$total] '$title' $*" >&2
	fail=true
}

for rev in $revisions; do
	n=$((n + 1))
	title=$(git log --format='%s' -1 "$rev")
	fail=false

	if [ "$(echo "$title" | wc -m)" -gt 72 ]; then
		err "title is longer than 72 characters, please make it shorter"
	fi
	if ! echo "$title" | grep -qE '^[a-z0-9,{}/_-]+: '; then
		err "title lacks a lowercase topic prefix (e.g. 'ipv6:')"
	fi
	if echo "$title" | grep -qE '^[a-z0-9,{}/_-]+: [A-Z][a-z]'; then
		err "title starts with an capital letter, please use lower case"
	fi
	if ! echo "$title" | grep -qE '[A-Za-z0-9]$'; then
		err "title ends with punctuation, please remove it"
	fi

	author=$(git log --format='%an <%ae>' -1 "$rev")
	if ! git log --format="%(trailers:key=Signed-off-by,only,valueonly,unfold)" -1 "$rev" |
			grep -qFx "$author"; then
		err "'Signed-off-by: $author' trailer is missing"
	fi

	for trailer in $(git log --format="%(trailers:only,keyonly)" -1 "$rev"); do
		if ! echo "$allowed_trailers" | grep -qFx "$trailer"; then
			err "trailer '$trailer' is misspelled or not in the sanctioned list"
		fi
	done

	git log --format="%(trailers:key=Fixes,only,valueonly,unfold)" -1 "$rev" > "$tmp"
	while read -r value; do
		if [ -z "$value" ]; then
			continue
		fi
		fixes_rev=$(echo "$value" | sed -En 's/([A-Fa-f0-9]{7,})[[:space:]]\(".*"\)/\1/p')
		if ! git cat-file commit "$fixes_rev" >/dev/null; then
			err "trailer 'Fixes: $value' does not refer to a known commit"
		fi
	done < "$tmp"

	body=$(git log --format='%b' -1 "$rev")
	body=${body%$(git log --format='%(trailers)' -1 "$rev")}
	if [ "$(echo "$body" | wc -w)" -lt 3 ]; then
		err "body has less than three words, please describe your changes"
	fi
	if ! [ "$(git log --format='%P' -1 "$rev" | wc -w)" = 1 ]; then
		err "merge commit found, please rebase your code"
	fi

	if [ "$fail" = true ]; then
		continue
	fi
	echo "ok    [$n/$total] '$title'"
	valid=$((valid + 1))
done

echo "$valid/$total valid commits"
if [ "$valid" -ne "$total" ]; then
	exit 1
fi
